---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 8192

provisioner:
  name: chef_zero

verifier:
  name: inspec
  deprecations_as_errors: true

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[mcrouter::default]
    attributes:
