---
driver:
  name: ec2
  require_chef_omnibus: true
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.2xlarge
  interface: public
  transport:
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  tags:
    Name: mcrouter-ubuntu-1404
    Type: test

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-9301c7f8
      tags:
        Name: mcrouter-default-ubuntu-1404
        Env: public

suites:
  - name: default
    run_list:
      - recipe[mcrouter::default]
    attributes:
