---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 8192

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[mcrouter::default]
    attributes:
