---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[mcrouter::default]
    attributes:
