---
driver:
  name: dokken
  privileged: true  # needed for sysctl changes

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
