---
driver:
  name: ec2
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  transport:
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-9301c7f8
      tags:
        Name: mcrouter-default-ubuntu-1404
        Env: public

suites:
  - name: default
    run_list:
      - recipe[mcrouter::default]
    attributes:
